/**
 * SORA — AI Learning Companion
 * Default Demo Data & Knowledge Base
 */

const SORA_DEMO_DATA = {
  user: {
    name: "Brian Dicky Vanka",
    npm: "24081010345",
    university: "UPN 'Veteran' Jawa Timur",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAwLWFH3DyRW1WRdbLUX87pxylybY596ritjULIJE1U5sInYMLs4oPZERnWuPtsfkuBJkEAphrIuR3tuWiUQ5mwL4Wa6N-bimL9xpkVxHL9610miBukEDyKB4cNszBDH3bVijslL6Ch3lPEzbcdN7KV8FXe4n1j9iXwSV3AGzkumDSep2-1lBeNHFOSE8VYVzRqtsrBGIzEP7sabuPWPS3L5VrwR25ej9LyQRWyIcxCu7KjzZuC9gxUhw",
    currentMood: "calm",
    studyMinutesToday: 32,
    studyMinutesTarget: 45,
    streakDays: 12,
    quizzesCompleted: 24,
    conceptsClarified: 68
  },

  materials: [
    {
      id: "mat_os_01",
      title: "Lecture 04: Operating Systems — Virtual Memory",
      course: "CS 301: Operating Systems",
      fileName: "Lecture_04_Operating_Systems.pdf",
      fileSize: "4.8 MB",
      uploadDate: "Kemarin, 14:20",
      totalPages: 32,
      estimatedTime: "24 min baca tenang",
      topicsCount: 5,
      status: "Analyzed",
      topics: [
        { id: "top_vm_01", name: "Virtual Memory & MMU Architecture", mastery: 85, status: "Mastered" },
        { id: "top_vm_02", name: "Paging, Page Tables & TLB Translation", mastery: 74, status: "In Progress" },
        { id: "top_vm_03", name: "Thrashing & Working Set Dynamics", mastery: 42, status: "Needs Review" },
        { id: "top_vm_04", name: "Page Replacement Algorithms (LRU, FIFO)", mastery: 65, status: "In Progress" },
        { id: "top_vm_05", name: "Demand Paging & Inverted Tables", mastery: 55, status: "In Progress" }
      ],
      contentSnippets: [
        {
          page: 4,
          topic: "Virtual Memory Architecture",
          text: "Virtual memory maps virtual addresses generated by the CPU into physical addresses in DRAM via the Memory Management Unit (MMU). This provides process isolation, uniform address space, and memory protection."
        },
        {
          page: 11,
          topic: "TLB Translation",
          text: "The Translation Lookaside Buffer (TLB) is an on-chip hardware cache for page table entries. A TLB hit avoids an extra memory access, executing in less than 1 nanosecond. A TLB miss requires walking multi-level page tables in main memory."
        },
        {
          page: 18,
          topic: "Thrashing & Working Set",
          text: "Thrashing occurs when the sum of the working sets of all active processes exceeds the total amount of available physical memory frames. The system spends more CPU time servicing page faults and swapping pages to/from disk than executing instructions, causing CPU utilization and throughput to collapse toward zero."
        },
        {
          page: 25,
          topic: "Page Replacement Algorithms",
          text: "Least Recently Used (LRU) replaces the page that has not been used for the longest period of time. It approximates the optimal MIN algorithm (Belady's anomaly-free) but incurs hardware overhead unless implemented with clock algorithm approximations."
        }
      ]
    },
    {
      id: "mat_dsa_01",
      title: "Data Structures: Self-Balancing Trees & Graphs",
      course: "CS 202: Data Structures & Algorithms",
      fileName: "DSA_Trees_and_Graphs.pdf",
      fileSize: "6.2 MB",
      uploadDate: "3 hari lalu",
      totalPages: 40,
      estimatedTime: "30 min baca tenang",
      topicsCount: 6,
      status: "Analyzed",
      topics: [
        { id: "top_dsa_01", name: "Binary Search Trees (BST) Traversal", mastery: 92, status: "Mastered" },
        { id: "top_dsa_02", name: "AVL Rotations & Balance Factors", mastery: 70, status: "In Progress" },
        { id: "top_dsa_03", name: "Dijkstra's Shortest Path Algorithm", mastery: 58, status: "Needs Review" },
        { id: "top_dsa_04", name: "Recursion & Call Stack Frames", mastery: 48, status: "Needs Review" },
        { id: "top_dsa_05", name: "Graph Adjacency Matrix vs List", mastery: 88, status: "Mastered" }
      ],
      contentSnippets: [
        {
          page: 6,
          topic: "AVL Rotations",
          text: "An AVL tree maintains height balance where the height difference between left and right subtrees (balance factor) never exceeds 1. Single rotations (LL, RR) and double rotations (LR, RL) restore balance in O(1) time after insertions or deletions."
        },
        {
          page: 19,
          topic: "Dijkstra's Algorithm",
          text: "Dijkstra's algorithm finds the shortest path in a weighted graph with non-negative edge weights using a greedy priority queue. It locks a node once visited with the lowest known distance. It fails with negative edges because earlier locked distances may become suboptimal later."
        },
        {
          page: 31,
          topic: "Recursion & Stack Frames",
          text: "Each recursive call allocates a stack frame containing local variables, parameters, and return address. Missing or ill-defined base cases cause infinite recursion and StackOverflowError. Call stack unwinding returns results back up the call tree."
        }
      ]
    }
  ],

  quizzes: [
    {
      id: "quiz_os_thrashing",
      materialId: "mat_os_01",
      title: "Operating Systems • Virtual Memory & Paging",
      topic: "Virtual Memory",
      difficulty: "Medium",
      questions: [
        {
          id: "q1",
          question: "Mengapa kondisi 'thrashing' terjadi pada sistem operasi ketika kebutuhan memori proses melebihi physical frames yang tersedia?",
          concept: "Thrashing & Working Set Dynamics",
          clue: "Bayangkan meja belajar yang terlalu penuh buku: kamu menghabiskan seluruh waktu untuk menukar buku yang terbuka daripada benar-benar membaca isinya.",
          options: [
            { id: "A", text: "Karena clock speed CPU otomatis menurun saat menerima lonjakan request I/O dari aplikasi." },
            { id: "B", text: "Sistem menghabiskan lebih banyak waktu untuk swap in/swap out halaman memori ke disk daripada mengeksekusi instruksi proses.", correct: true },
            { id: "C", text: "Bandwidth memory bus mengalami saturasi akibat thread lock konkurensi yang tidak teratur." },
            { id: "D", text: "Alamat virtual menimpa tabel halaman fisik yang tersimpan di dalam cache L1/L2." }
          ],
          explanation: "Thrashing terjadi saat working set gabungan melebihi physical RAM. Akibatnya tiap proses terus-menerus memicu Page Fault, sehingga CPU sibuk mengantre transfer disk I/O dan utilisasi CPU anjlok ke mendekati 0%."
        },
        {
          id: "q2",
          question: "Apa fungsi utama dari Translation Lookaside Buffer (TLB) dalam manajemen memori virtual?",
          concept: "TLB & Address Translation",
          clue: "TLB berperan seperti catatan kecil saku di samping CPU agar tidak perlu bolak-balik memeriksa buku tebal di rak utama.",
          options: [
            { id: "A", text: "Menyimpan backup isi seluruh RAM ke storage SSD secara berkala." },
            { id: "B", text: "Hardware cache cepat yang menyimpan pemetaan alamat virtual ke nomor frame fisik terbaru untuk menghindari akses memori bertingkat.", correct: true },
            { id: "C", text: "Mendeteksi virus dan fragmentasi pada swap partition secara otomatis." },
            { id: "D", text: "Mengompresi data pada frame yang tidak aktif agar menghemat RAM." }
          ],
          explanation: "TLB adalah associative cache berkecepatan sangat tinggi pada MMU yang menyimpan translasi Page Number -> Frame Number terakhir, memangkas kebutuhan multi-level memory lookups."
        },
        {
          id: "q3",
          question: "Dalam algoritma Page Replacement LRU (Least Recently Used), halaman mana yang akan digantikan ketika terjadi Page Fault dan frame penuh?",
          concept: "Page Replacement Algorithms",
          clue: "Perhatikan kata 'Recently': lihat ke masa lalu, halaman mana yang paling lama tidak disentuh oleh program.",
          options: [
            { id: "A", text: "Halaman yang pertama kali dialokasikan saat program dibuka (urutan kedatangan tertua)." },
            { id: "B", text: "Halaman yang memiliki ukuran byte terbesar di dalam memory frame." },
            { id: "C", text: "Halaman yang referensi akses terakhirnya memiliki jarak waktu terlama dari waktu saat ini.", correct: true },
            { id: "D", text: "Halaman yang berada pada indeks teratas dari heap memori." }
          ],
          explanation: "LRU mengevaluasi waktu akses terakhir dan menukar halaman yang paling lama tidak diakses. Ini mematuhi prinsip lokalitas temporal."
        }
      ]
    },
    {
      id: "quiz_dsa_recursion",
      materialId: "mat_dsa_01",
      title: "Data Structures • Graph Theory & Recursion",
      topic: "Graph Theory & Dijkstra",
      difficulty: "Medium",
      questions: [
        {
          id: "q1",
          question: "Mengapa algoritma Dijkstra gagal menjamin jalur terpendek apabila graf memiliki edge dengan bobot negatif?",
          concept: "Dijkstra Greedy Invariant",
          clue: "Dijkstra bersikap serakah (greedy) dan mengunci jarak suatu node begitu selesai dikunjungi tanpa pernah memperbarui node terkunci tersebut.",
          options: [
            { id: "A", text: "Karena priority queue tidak dapat menyimpan bilangan integer bertanda negatif." },
            { id: "B", text: "Dijkstra mengasumsikan jarak node yang telah dikunjungi (marked finalized) tidak akan pernah menjadi lebih pendek melalui rute alternatif di masa depan.", correct: true },
            { id: "C", text: "Algoritma akan langsung memicu error stack overflow karena rekursi tak berhingga." },
            { id: "D", text: "Bobot negatif otomatis mengubah graf terarah menjadi graf tidak terarah." }
          ],
          explanation: "Prinsip greedy Dijkstra mengunci jarak node terdekat. Jika di kemudian hari ada bobot negatif yang membuat rute memutar bernilai lebih kecil, Dijkstra tidak akan mengevaluasi ulang node yang sudah ditandai 'finalized'."
        },
        {
          id: "q2",
          question: "Apa konsekuensi langsung jika fungsi rekursif tidak memiliki base case yang valid atau kondisi base case tidak pernah tercapai?",
          concept: "Recursion & Stack Frames",
          clue: "Setiap panggilan rekursif menumpuk satu piring baru di atas meja lemari sampai lemari runtuh.",
          options: [
            { id: "A", text: "Program mengembalikan nilai null secara otomatis tanpa memicu error." },
            { id: "B", text: "Frame memori stack terus bertambah hingga melebihi batas alokasi memori panggilan, memicu StackOverflowError.", correct: true },
            { id: "C", text: "CPU akan otomatis mengalihkan eksekusi menjadi iterasi loop for." },
            { id: "D", text: "Data di dalam heap memory akan terhapus seketika oleh Garbage Collector." }
          ],
          explanation: "Fungsi rekursif tanpa base case terus menambah stack frame ke memori stack untuk menyimpan variabel lokal dan return address hingga memori stack habis (StackOverflowError)."
        }
      ]
    }
  ],

  topicMapNodes: [
    {
      id: "node_os_arch",
      label: "OS Architecture",
      subtitle: "Core Knowledge Root",
      tier: 0,
      x: 170,
      y: 55,
      mastery: 100,
      status: "Mastered",
      desc: "Fondasi sistem operasi yang menjembatani abstraksi perangkat keras, kernel privilege modes, dan system call interface."
    },
    {
      id: "node_mem_mgmt",
      label: "Memory Management",
      subtitle: "Virtual & Physical Subsystems",
      tier: 1,
      x: 75,
      y: 140,
      mastery: 68,
      status: "In Progress",
      parent: "node_os_arch",
      desc: "Alokasi memori, paging, segmentasi, MMU, dan manajemen memori virtual."
    },
    {
      id: "node_sched",
      label: "Process Scheduling",
      subtitle: "CPU Multitasking & Queues",
      tier: 1,
      x: 265,
      y: 140,
      mastery: 84,
      status: "Mastered",
      parent: "node_os_arch",
      desc: "Algoritma scheduling CPU: Round Robin, Shortest Job First, Multilevel Feedback Queue."
    },
    {
      id: "node_tlb",
      label: "TLB & Page Tables",
      subtitle: "Address Translation Cache",
      tier: 2,
      x: 65,
      y: 235,
      mastery: 74,
      status: "In Progress",
      parent: "node_mem_mgmt",
      desc: "Penerjemahan alamat cepat melalui associative cache TLB dan multi-level page tables."
    },
    {
      id: "node_thrashing",
      label: "Thrashing & Working Set",
      subtitle: "Paging Collapse Mechanics",
      tier: 2,
      x: 120,
      y: 290,
      mastery: 42,
      status: "Needs Review",
      parent: "node_mem_mgmt",
      desc: "Fenomena kolaps throughput akibat page faults yang membanjiri bus I/O storage."
    },
    {
      id: "node_concurrency",
      label: "Concurrency & Locks",
      subtitle: "Semaphores & Mutexes",
      tier: 1,
      x: 170,
      y: 345,
      mastery: 60,
      status: "In Progress",
      parent: "node_os_arch",
      desc: "Sinkronisasi antar-thread, critical sections, deadlock conditions, dan atomic operations."
    },
    {
      id: "node_deadlock",
      label: "Deadlock Detection",
      subtitle: "Banker's Algorithm & Prevention",
      tier: 2,
      x: 95,
      y: 425,
      mastery: 48,
      status: "Needs Review",
      parent: "node_concurrency",
      desc: "4 kondisi Coffman penentu deadlock dan strategi pencegahan serta pemulihan."
    },
    {
      id: "node_threads",
      label: "Thread Pools & Fibers",
      subtitle: "Lightweight Execution Units",
      tier: 2,
      x: 245,
      y: 425,
      mastery: 90,
      status: "Mastered",
      parent: "node_concurrency",
      desc: "Manajemen thread level user dan kernel, thread lifecycle, dan optimasi pool."
    }
  ],

  recommendations: {
    dailyFocus: {
      topic: "Recursion & Stack Frames",
      course: "CS 202: Data Structures & Algorithms",
      targetTime: "12 mindful minutes",
      reason: "Berdasarkan kuis terakhir, kamu ragu saat mengevaluasi unwinding call stack dan base cases. Memperjelas ini sekarang akan membuat materi tree traversal dan AVL terasa sangat ringan besok.",
      weakConcepts: [
        "Call stack memory allocation & unwinding logic",
        "Korelasi erat dengan Ujian Tengah Semester (Soal #3)"
      ]
    },
    alternateFocus: {
      topic: "Thrashing & Working Set Dynamics",
      course: "CS 301: Operating Systems",
      targetTime: "10 mindful minutes",
      reason: "Hasil evaluasi kuis Operating Systems menunjukkan pemahaman konsep paging sudah baik (74%), namun batas ambang thrashing masih perlu penguatan visual.",
      weakConcepts: [
        "Keseimbangan working set proses vs physical frames",
        "Penanganan page replacement frequency"
      ]
    }
  }
};
